
name: irsa_kitchen_offline
description: Offline menu app for Irsa's Kitchen
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15

flutter:
  uses-material-design: true
  assets:
    - assets/menu.json
